# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

- Infrastructure:
    - Traefik:
        icon: traefik.svg
        href: https://traefik.vikassaini.info/
        statusStyle: "dot"
        widget:
          type: traefik
          url: http://traefik:8080
    - Portainer:
        icon: portainer.svg
        href: https://portainer.vikassaini.info/
        widget:
          type: portainer
          url: http://portainer:9000
          env: 2
          key: ptr_xxz/FKQlwH2L2WO3FnhYkindFOA6k8XwF73s7pOzFhI=

- Applications:
    - SearXNG:
        icon: searxng.png
        href: https://searxng.vikassaini.info/
        server: server-docker
        container: searxng
