# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

- Infrastructure:
    - Traefik:
        icon: traefik.svg
        href: https://traefik.vikassaini.info/
        widget:
          type: traefik
          url: http://traefik:8080
    - Portainer:
        icon: portainer.svg
        href: https://portainer.vikassaini.info/
        widget:
          type: portainer
          url: http://portainer:9000
          env: 1
          key: ptr_xxz/FKQlwH2L2WO3FnhYkindFOA6k8XwF73s7pOzFhI=
