# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

- Infrastructure:
    - Traefik:
        icon: traefik.svg
        href: https://traefik.vikassaini.info/
        description: pve1
        widget:
            type: traefik
            url: http://traefik:8080